In [2]:
import numpy as np 


x = np.array(([1, 2, 3],[4,5,6] ))

np.ndim(x) # number of dimensions

2

In [3]:
identity_matrix = np.eye(2) # identity matrix of size 2x2
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


In [6]:
full_matrix = np.full((2,3),7) # 2x2 matrix filled with 7s
print(full_matrix)

[[7 7 7]
 [7 7 7]]


In [14]:
floating_array = np.array(([1, 2],[3, 4])) # create a 2D array

float_matrix = np.float16(floating_array)# convert to float
print(float_matrix)

[[1. 2.]
 [3. 4.]]


In [ ]:
arranged_array = np.arange(100,600,100)  # array from 100 to 500 with step of 100
print(arranged_array)

[100 200 300 400 500]


In [19]:
y = np.array(([10,20],[30,40]))
z = np.array(([5,15],[25,35]))

result = y * z 
print(result)

[[  50  300]
 [ 750 1400]]
